"""
AI's ORIGINAL solution (as returned by the AI tool, unmodified).

BUGS PRESENT IN THIS VERSION (intentionally left in for Step 2):
  1. Output layer uses `sigmoid` instead of `softmax` for a 3-class,
     mutually-exclusive classification problem.
  2. Loss function is `mean_squared_error` instead of `categorical_crossentropy`,
     which is the wrong loss for a classification task with one-hot labels.

These were the actual mistakes generated by the AI tool for this prompt.
"""

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

# --- Synthetic dataset -------------------------------------------------
np.random.seed(1)
n = 500
order_value = np.random.uniform(50, 1000, n)
distance_km = np.random.uniform(1, 30, n)
prep_time_min = np.random.uniform(5, 45, n)

priority = []
for v, d, p in zip(order_value, distance_km, prep_time_min):
    score = v / 200 + d / 10 + p / 15
    if score < 5:
        priority.append(0)
    elif score < 8:
        priority.append(1)
    else:
        priority.append(2)
priority = np.array(priority)

X = np.column_stack([order_value, distance_km, prep_time_min])
y = to_categorical(priority, num_classes=3)

split = int(0.8 * n)
X_train, X_val = X[:split], X[split:]
y_train, y_val = y[:split], y[split:]

# --- Model ---------------------------------------------------------------
model = Sequential([
    Dense(32, activation="relu", input_shape=(3,)),
    Dense(16, activation="relu"),
    Dense(3, activation="sigmoid"),   # <-- BUG: should be softmax
])

model.compile(optimizer="adam", loss="mean_squared_error", metrics=["accuracy"])  # <-- BUG: wrong loss

history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=20,
    verbose=1,
)

# --- Plot loss curves ------------------------------------------------------
fig, axes = plt.subplots(1, 2, figsize=(10, 4))
axes[0].plot(history.history["loss"])
axes[0].set_title("Training Loss")
axes[0].set_xlabel("Epoch")
axes[0].set_ylabel("Loss")

axes[1].plot(history.history["val_loss"])
axes[1].set_title("Validation Loss")
axes[1].set_xlabel("Epoch")
axes[1].set_ylabel("Loss")

plt.tight_layout()
plt.savefig("ai_original_loss_curves.png")

# --- Save, reload, predict --------------------------------------------------
model.save("food_priority_model.keras")
reloaded = load_model("food_priority_model.keras")

sample = np.array([[500, 10, 20]])
prediction = reloaded.predict(sample)
print("Predicted priority probabilities:", prediction)
print("Predicted class:", np.argmax(prediction))
